import {MarketInput,Signal,Decision,Side} from "./types";
const clamp=(n:number,a=0,b=100)=>Math.max(a,Math.min(b,n));
const sig=(module:string,side:Side,score:number,reason:string,ts:number):Signal=>({module,side,score:clamp(score),reason,ts});
export function momentum(x:MarketInput){const d=x.emaFast-x.emaSlow;if(Math.abs(d)/x.price<0.00025)return sig("crypto-momentum","NO_TRADE",35,"EMA farkı zayıf",x.ts);return sig("crypto-momentum",d>0?"LONG":"SHORT",clamp(55+Math.abs(d)/x.price*5000+x.volumeZ*6),"EMA+hacim momentumu",x.ts)}
export function reversal(x:MarketInput){if(x.rsi<28&&x.buyPressure>x.sellPressure*1.12)return sig("reversal-detector","LONG",72,"Aşırı satım + alıcı dönüşü",x.ts);if(x.rsi>72&&x.sellPressure>x.buyPressure*1.12)return sig("reversal-detector","SHORT",72,"Aşırı alım + satıcı dönüşü",x.ts);return sig("reversal-detector","NO_TRADE",40,"Dönüş teyidi yok",x.ts)}
export function orderbook(x:MarketInput){const r=(x.bidDepth+1)/(x.askDepth+1);if(r>1.25)return sig("orderbook-pressure","LONG",clamp(55+(r-1)*45),"Bid derinliği baskın",x.ts);if(r<0.8)return sig("orderbook-pressure","SHORT",clamp(55+(1-r)*45),"Ask derinliği baskın",x.ts);return sig("orderbook-pressure","NO_TRADE",35,"Order book dengeli",x.ts)}
export function liquidation(x:MarketInput){const t=x.longLiq+x.shortLiq+1;if(x.shortLiq/t>.67)return sig("liquidation-radar","LONG",68,"Short likidasyon yoğunluğu",x.ts);if(x.longLiq/t>.67)return sig("liquidation-radar","SHORT",68,"Long likidasyon yoğunluğu",x.ts);return sig("liquidation-radar","NO_TRADE",35,"Likidasyon üstünlüğü yok",x.ts)}
export function fakeBreakout(x:MarketInput){const extreme=x.volumeZ>2.2&&Math.abs(x.buyPressure-x.sellPressure)<.08*Math.max(x.buyPressure,x.sellPressure);return sig("fake-breakout",extreme?"NO_TRADE":"NO_TRADE",extreme?88:25,extreme?"Yüksek hacim fakat akış teyitsiz: breakout riski":"Fake breakout alarmı yok",x.ts)}
export function decide(x:MarketInput,now=Date.now()):Decision{const age=now-x.ts;if(age>2500)return{side:"NO_TRADE",confidence:0,reasons:[`Veri eski: ${age}ms`],fresh:false};const s=[momentum(x),reversal(x),orderbook(x),liquidation(x),fakeBreakout(x)];if(s.find(v=>v.module==="fake-breakout"&&v.score>=80))return{side:"NO_TRADE",confidence:20,reasons:s.map(v=>v.reason),fresh:true};const active=s.filter(v=>v.side!=="NO_TRADE");const L=active.filter(v=>v.side==="LONG"),S=active.filter(v=>v.side==="SHORT");const ls=L.reduce((a,v)=>a+v.score,0),ss=S.reduce((a,v)=>a+v.score,0);if(!active.length||Math.min(ls,ss)>0&&Math.abs(ls-ss)<55)return{side:"NO_TRADE",confidence:35,reasons:["Sinyaller çelişkili / yetersiz",...s.map(v=>v.reason)],fresh:true};const side:Side=ls>ss?"LONG":"SHORT", win=side==="LONG"?ls:ss, lose=side==="LONG"?ss:ls;const conf=clamp(50+(win-lose)/Math.max(1,active.length));if(conf<68)return{side:"NO_TRADE",confidence:conf,reasons:["Minimum güven eşiği aşılmadı",...s.map(v=>v.reason)],fresh:true};const risk=x.price*Math.max(.0015,x.atrPct*1.15);return{side,confidence:conf,reasons:s.map(v=>v.reason),fresh:true,entry:x.price,stop:side==="LONG"?x.price-risk:x.price+risk,target1:side==="LONG"?x.price+risk*1.2:x.price-risk*1.2,target2:side==="LONG"?x.price+risk*2:x.price-risk*2}}
